### ISSUE TITLE
Website is currently down

### ISSUE THREAD

**Issue by rennyhoang** [xflea/nv-dashboard-header-maker#1]
The link to the GitHub pages doesn’t lead anywhere

**Comment by xflea** [comment]
> The link to the GitHub pages doesn’t lead anywhere

Hi, thanks for reporting.
I managed to do some tinkering with the Custom DNS option of GitHub Pages and forgot to reset all the settings, now I did, the issue should be fixed as soon as GitHub restore the default address of my website (which is hosted using GitHub Pages).

**Comment by xflea** [comment]
The default address has been restored, closing the issue.
